CREATE TABLE IF NOT EXISTS users (
     id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     first_name TEXT,
     last_name  TEXT,
     username  TEXT,
     password TEXT,
     email TEXT,
     phone TEXT,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UNIQUE (username, email)
);

CREATE TABLE IF NOT EXISTS bills (
     id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id INT NOT NULL REFERENCES users (id),
     title TEXT,
     description TEXT,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     created_by INT DEFAULT NULL,
     updated_by INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS medias (
    url TEXT,
    bill_id       INT NOT NULL REFERENCES bills (id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INT DEFAULT NULL,
    updated_by INT DEFAULT NULL
);